![](https://sun9-1.userapi.com/impf/ZRocoBpOifxjb8y4tbaAV3GR8VVelfyYOT8XUg/00JGtzKDVMw.jpg?size=744x670&quality=96&proxy=1&sign=4e31bf9fe77c13f007d6e82b67ac02c8&type=album)
![](https://sun9-58.userapi.com/impf/yVZoLm6ZWacjfEycgQeCyBrx68uOauCNDqkxSg/9iNy3_aR_dY.jpg?size=727x431&quality=96&proxy=1&sign=4e3f8453cd3f1ad96a477dfa02cb8752&type=album)
![](https://sun9-74.userapi.com/impf/3G05QnTWGVExX4c_eKXFBbFmc2VMj3Ssrt5s_Q/ZfjcjgcIgjo.jpg?size=719x217&quality=96&proxy=1&sign=35e306053ff70d61d769e21a5a60bc62&type=album)

In [2]:
import numpy as np

In [3]:
def is_invertible(A_inv: np.array, x: np.array, i: int) -> None:
    i -= 1
    
    #### STEP 1 ####
    l = np.dot(A_inv, x)
    
    
    #### STEP 2 ####
    if l[i] == 0:
        print("NO")
        return
    l_wave = l.copy()
    l_wave[i] = -1
    
    
    #### STEP 3 ####
    l_caret = l_wave/(-l[i])
    
    
    #### STEP 4 ####
    Q = np.identity(len(A))
    Q[:, i] = l_caret
    
    
    #### STEP 5 ####
    numpy_mul_result = Q.dot(A_inv)
    print(numpy_mul_result)
    
    my_mul_result = np.zeros((len(A), len(A)))
    
    for n in range(len(A_inv)):
        for m in range(len(A_inv)):
#             print(f"[{n}][{m}] = {Q[n,n]} * { A_inv[n,m]} + {Q[n,i]} * {A_inv[i, m]}")
            if i == n:
                my_mul_result[n, m] = Q[n,n] * A_inv[n,m]
                continue
            my_mul_result[n, m]= Q[n,n] * A_inv[n,m] + Q[n,i] * A_inv[i, m]   
            
    print(my_mul_result)
    
    print("YES")
    return

In [4]:
i = 3
A = np.array([[1, -1, 0],
     [0, 1, 0],
     [0, 0, 1]])
A_inv = np.array([[1, 1, 0],
                 [0, 1, 0],
                 [0, 0, 1]])
x = np.array([1, 0, 1])

In [5]:
is_invertible(A_inv, x, i)

[[ 1.  1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
YES


In [6]:
i = 3
A = np.array([[1, -1, 0],
     [0, 1, 0],
     [0, 1, 1]])
A_inv = np.array([[1, 1, 0],
                 [0, 1, 0],
                 [0, -1, 1]])
x = np.array([0, 1, 1])

In [7]:
is_invertible(A_inv, x, i)

NO


In [8]:
i = 2
A = np.array([[1, 0, 5],
     [2, 1, 5],
     [3, 4, 0]])
A_inv = np.array([[-24, 20, -5],
                 [18, -15, 4],
                 [5, -4, 1]])
x = np.array([2, 2, 2])

In [9]:
is_invertible(A_inv, x, i)

[[-0.85714286  0.71428571  0.14285714]
 [ 1.28571429 -1.07142857  0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]
[[-0.85714286  0.71428571  0.14285714]
 [ 1.28571429 -1.07142857  0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]
YES
